### ISSUE TITLE
Needle Bounce with zero()

### ISSUE THREAD

**Issue by coultl6556** [clearwater/SwitecX25#22]
When I run the zero() function the needle bounces off the stop and (sometimes) ends up landing at a position above the stop. I'm running a boost gauge so it's always at zero when I shut the car off. 

Any suggestions for how I can modify the zero function to reduce the needle bounce? Can I reduce the number of backward steps it takes or add more time between each step? Seems like a small change would fix as I think this is caused by some kind of resonance. 

Thank you!

**Comment by coultl6556** [comment]
FYI, here’s a video of the application: https://youtu.be/XPYAwQu61e4

Replaced the factory clock with a scratch build boost gauge and data readout.

**Comment by guyc** [comment]
I can think of two approaches - do a full-scale sweep (you see this often in car dashes) which, since your needle is usually at 0 on power-on will not grind against the stops at all.  This assumes you have both low and high hard-stops, which isn't always the case.

I know some people do not like the sweep - I was just having this discussion regarding a boost gauge for a classic car, and the builder did not want a sweep because the original vehicle did not do one.  

The other approach is to use an accelerated zero function instead of the fixed-step-time zero function that is provided by default.  Something like this instead of `motor1.zero();`
```
motor1.currentStep = motor1.steps;  // tell the motor it is already at full-scale deflection
motor1.setPosition(0);  // and that you want to go to 0
while (!motor1.stopped()) motor1.update();  // spin it backwards using the acceleration table until it gets to 0
```

That should at least have _different_ resonance characteristics.  It might be better?

**Comment by coultl6556** [comment]
Awesome. Will try that. 

Quick question. Is there a way I can just move the needle back one step instead of running zero? Just one step backwards at each startup would be enough.

**Comment by guyc** [comment]
Sure:
```
motor1.currentStep = 1;  // tell the motor it is at position 1
motor1.setPosition(0);  // and that you want to go to 0
while (!motor1.stopped()) motor1.update();  // spin it backwards using the acceleration table until it gets to 0
```

**Comment by coultl6556** [comment]
Thank you. I messing something up bc I get the following compilation error when I put that code in setup. 

`C:\Users\coult\Documents\Arduino\URS6_V6\URS6_V6.ino: In function 'void setup()':
C:\Users\coult\Documents\Arduino\URS6_V6\URS6_V6.ino:127:26: error: expression cannot be used as a function
   while (!motor1.stopped()) motor1.update();  // spin it backwards using the acceleration table until it gets to 0
                          ^

exit status 1

Compilation error: expression cannot be used as a function`

**Comment by guyc** [comment]
Well one of us messed something up, but it wasn't you.  Try:
```
 while (!motor1.stopped) motor1.update(); 
```

**Comment by coultl6556** [comment]
Works perfectly. I ended up at 5 steps and it great for my application. There's now only a tiny audible tick where the zero() was pretty loud. The needle does not bounce at all now. The 5 steps are more than enough to make up for any steps that might get missed resulting in the needle not being at zero when I shut down. Here's the code I used: 

  ```
motor1.currentStep = 5;  // tell the motor it is at position 1
  motor1.setPosition(0);  // and that you want to go to 0
  while (!motor1.stopped) motor1.update();   // spin it backwards using the acceleration table until it gets to 0
```
